### PR TITLE
Allow to specify project in unite source

### PR DESCRIPTION
**Pull request by m42e**
As in the github source, you can use `Unite issue:jira:MYPROJECT` to limit the scope to MYPROJECT

### CODE REVIEW

**Comment by rafi** [comment]
Thanks :+1:

**Comment by rafi** [comment]
Had to revert this because it broke the plugin for me. Had a duplicate `AND AND` between two arguments.

**Comment by m42e** [comment]
Can you provide me a sample, so I can fix it?

**Comment by m42e** [comment]
Ah, ok got it

**Comment by rafi** [comment]
With command: `Unite issue:jira` the generated JQL is: `assignee=My.Name+AND++AND+resolution=unresolved` which is invalid and fails the request.

**Pull request merged**
